### ISSUE TITLE
Add telegram import to bot

### ISSUE THREAD

**Issue by D4ndellion** [turt2live/matrix-sticker-manager#14]
Would allow self service importing of telegram stickerpacks

**Comment by turt2live** [comment]
This is the responsibility of another party or project, not the sticker manager. The sticker manager is an implementation of a Matrix spec proposal to prove that the specification works, as well as provide a simple bot to manage native sticker packs. The format exposed by the API is (in future) intended to be used by other projects which may support importing and sharing of sticker packs.

**Comment by D4ndellion** [comment]
I'll try implement a tool to import telegram into such a room then!

**Comment by turt2live** [comment]
fwiw if you tack `.json` onto the end of any stickerpack URL, you'll see the format I'm talking about.

**Comment by D4ndellion** [comment]
How long is the `.json` cached? Would it be possible to return a dummy json and later change it?

**Comment by turt2live** [comment]
The important part at the moment is really just the `io.t2bot.dimension` part - it is cached indefinitely. The meat of the sticker pack is actually contained in the room referenced there.

**Comment by D4ndellion** [comment]
So the stickerpicker doesn't use the stickers array to load the stickers?

**Comment by turt2live** [comment]
Nope, that's there as experimental reference. It's also not used in the final proposal (which this doesn't fully support either): https://github.com/matrix-org/matrix-doc/pull/1951

**Comment by D4ndellion** [comment]
I see, I misunderstood the architecture.

I thought it was stickerpicker->json->sticker-manager->matrix room

i.e the sticker-manager _happened_ to be backed by a matrix room, but could really be anything as long as it returned valid json.

I do like the proposal though, now that I've done a quick read of it

**Comment by MurzNN** [comment]
> I'll try implement a tool to import telegram into such a room then!

@dali99 did you have any results with implementing Telegram stickers import tool?
