### ISSUE TITLE
can't start docker

### ISSUE THREAD

**Issue by hellEVIL-13** [turt2live/matrix-sticker-manager#18]
(node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/etc/stickerbot/data/bot.json'
    at Object.openSync (fs.js:438:3)
    at writeFileSync (fs.js:1189:35)
    at FileSync.read (/app/node_modules/lowdb/adapters/FileSync.js:46:9)
    at LodashWrapper.db.read (/app/node_modules/lowdb/lib/main.js:32:21)
    at module.exports (/app/node_modules/lowdb/lib/main.js:51:13)
    at new SimpleFsStorageProvider (/app/node_modules/matrix-bot-sdk/lib/storage/SimpleFsStorageProvider.js:9:19)
    at /app/lib/index.js:34:22
    at Generator.next (<anonymous>)
    at fulfilled (/app/lib/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by turt2live** [comment]
That looks like you haven't specified the volume for it to use

**Comment by hellEVIL-13** [comment]
And where can I get it? Or how to create an example?

**Comment by turt2live** [comment]
The full commands for Docker are in the readme. The "building your own" steps also cover the default config and appservice registration.

**Comment by hellEVIL-13** [comment]
This I saw, not start because of this no such file or directory, open '/etc/stickerbot/data/bot.json'
Where to get this file?

**Comment by turt2live** [comment]
You'll need to specify the data directory in the config to be /data

**Comment by hellEVIL-13** [comment]
I understood this, I did not understand what this file should contain

**Comment by turt2live** [comment]
Change `dataPath` in your config to `/app/storage`

**Comment by hellEVIL-13** [comment]
Hurray works, many thanks !!!
