### ISSUE TITLE
Can't pass app authentification

### ISSUE THREAD

**Issue by Vos68** [turt2live/matrix-sticker-manager#19]
Hello there! 
installed and setted up matrix-synapse server + dimension + web-riot + sticker-manager
Everything works like charm, but facing a problem  -
Sticker manager cannot authorise as app service with such a error -
MatrixLiteClient (REQ-2 RESP-H404) { errcode: 'M_NOT_FOUND', error: 'Account data not found' }
MatrixLiteClient (REQ-2) { errcode: 'M_NOT_FOUND', error: 'Account data not found' }
StickerStore No account data or error retrieving store - returning
StickerStore Loaded 0 known packs
I've added application service in matrix config, generated to different access tokens - everything by manuals, but something going wrong
If i try to register user @stickers:matrix.myhomeserver.com - its respond with error that user id is reserved for app service.

**Comment by turt2live** [comment]
That error looks harmless to me. It's just saying it hasn't ever been used before.

**Comment by Vos68** [comment]
But than bot should connect as @stickers:matrix.myserver.com and answer on request like "!stickers help" in private room with bot? 

A bit more info about my config - 
in homeserver.yaml i added 
app_service_config_files:
   - /etc/matrix-synapse/stickers_app_registration.yaml

In stickers_app_registration.yaml i witten -

id: sticker-manager
url: https://stickers.homeserver.com
as_token: "30c05ae90a248a4188e620216fa72e349803310ec83e2a77b34f22183efd404ec1cd22d2ffa4bbc76a8c1ccf541dd692eee90be6081f46"
hs_token: "312df522183efd404ec1cd22d2ffa4bbc76a8c1ccf541dd692eef281356bb74e30c05ae90a248a4188e620216fa72e349803310ec83e2a77b34"
sender_localpart: "stickers"
namespaces:
  users: []
  rooms: []
  aliases:
    - exclusive: true
      regex: "#_stickerpack_.+:matrix.homeserver.com"

**Comment by turt2live** [comment]
You'll need to change the `as_token` and `hs_token` now that you've publicly disclosed what they are.

If you've restarted Synapse and the bot still isn't replying to new invites (old ones from before the restart might not work), then you'll have to look at the Synapse logs to see what is going wrong.

**Comment by Vos68** [comment]
Thank You, Travis! Seems adding bot to private chat again worked for me! And i've got my very first sticker! 
Appreciate your concern about security - obviously tokens will be changed!
One question - not exactly about that bot, but about dimension and stickers - 
why i dont see any default stickers ? 
<img width="877" alt="Screen Shot 2019-08-08 at 17 00 17" src="https://user-images.githubusercontent.com/2140251/62709523-372c6980-b9fe-11e9-92a1-7897fd9b1ce4.png">

**Comment by turt2live** [comment]
That looks like a misconfigured homeserver. If it's a private homeserver, it might not be able to reach t2bot.io (the server where the images are located).

**Comment by Vos68** [comment]
Yes, i have a private server. I changed all paths in configs from "...t2bot.io..." to "..myhomeserver.com..". Sadly, i was expecting that dimension have that basic stickerpacks "on-board" and i can direct all links to homeserver.  
So, do i understand correct - matrix server or demension manager doesn't include stickers images itself and all pics should be loaded from outside of private network form t2bot.io?

**Comment by turt2live** [comment]
The default sticker packs are hosted off t2bot.io but anything else is hosted off the server that created the sticker pack. https://github.com/turt2live/matrix-dimension/issues/247 is the issue for fixing this.

**Comment by Vos68** [comment]
Ok, got it! Thank You, Travis - your answers helped to figure out blindspots of my understanding!
